<?php

return array(
    'enum_btx_meio_fav_contato' => ["3659"=>"Whatsapp","3661"=>"E-mail","3663"=>"Telefone"],
    'enum_btx_regiao_procura_imovel' => ["779"=>"Região Alfa","781"=>"Região Beta","783"=>"Região Gama","785"=>"Região Delta","787"=>"Região Epsilon","789"=>"Região Zeta","791"=>"Região Eta","793"=>"Região Teta","795"=>"Não sei"],
    'enum_btx_dormitorios' => ["765"=>"Kitnet","767"=>"1 dorm.","769"=>"2 dorm.","771"=>"3 dorm."],
    'enum_btx_possui_mobilias' => ["773"=>"Semi mobiliado","775"=>"Mobiliado","777"=>"Sem mobília"],
    'enum_btx_faixa_valor_aluguel' => ["719"=>"Até R$1.000,00","721"=>"de R$1.000,01 até R$1.500,00","723"=>"Entre R$1.500,01 à R$2.500,00","725"=>"Entre R$2.500,01 à R$3.500,00","727"=>"Entre R$3.500,01 à R$5.000,00","729"=>"Acima de R$5.000,00"],
    'enum_btx_previsao_mudanca' => ["731"=>"Até 10 dias","733"=>"de 11 à 20 dias","735"=>"de 21 à 30 dias","737"=>"de 31 à 50 dias","739"=>"de 51 à 60 dias","741"=>"em mais de 60 dias"],
    'enum_btx_possui_fiador' => ["749"=>"Sim","751"=>"Não"],
    'enum_btx_tipo_lead' => ["2265"=>"Aluguel","2267"=>"Vendas","Venda"=>"Vendas","CaptacaoLocacao"=>"Captacao Locacao","2269"=>"Captacao Locacao","CaptacaoVendas"=>"Captacao Vendas","2277"=>"Captacao Vendas","7083"=>"Aluguel_Especial","AluguelEspecial"=>"Aluguel_Especial"],
    'array_tipo_origembtx' => array(
        "Aluguel"=> array(
            "OLX"=>["origem"=>"Portais","suborigem"=>"OLX"],
            "CHAMADA"=>["origem"=>"Telefone(Receptivo)","suborigem"=>""],
            "VIVA REAL"=>["origem"=>"Portais","suborigem"=>"VivaReal"],
            "IMÓVEL WEB"=>["origem"=>"Portais","suborigem"=>"ImovelWeb"],
            "CHAVES NA MÃO"=>["origem"=>"Portais","suborigem"=>"ChavesNaMao"],
            "MERCADO LIVRE"=>["origem"=>"Portais","suborigem"=>"MercadoLivre"],
            "ZAP IMÓVEIS"=>["origem"=>"Portais","suborigem"=>"ZapImoveis"],
            "FORMULÁRIO DE LOCAÇÃO"=>["origem"=>"SiteLocacao","suborigem"=>""],
            "FORMULÁRIO BUSCA PARA MIM"=>["origem"=>"SiteBusquepMim","suborigem"=>""],
            "FORMULÁRIO DE LEADS"=>["origem"=>"Campanhas","suborigem"=>""],
            "FORMULÁRIO DE LOCAÇÃO"=>["origem"=>"SiteLocacao","suborigem"=>""],
            "FORMULÁRIO DE LOCAÇÃO - HOTSITE COMERCIAL"=>["origem"=>"SiteLocacaoComercial","suborigem"=>""],
            "FORMULÁRIO CAPTAÇÃO VENDAS"=>["origem"=>"","suborigem"=>""],
            "FORMULÁRIO DE CAPTAÇÃO"=>["origem"=>"","suborigem"=>""],
            "BLIP"=>["origem"=>"Blip","suborigem"=>""],
            "EMPREENDIMENTO ALFA"=>["origem"=>"Empreendimento_Alfa","suborigem"=>""],
            "EMPREENDIMENTO BETA"=>["origem"=>"Empreendimento_Beta","suborigem"=>""],
        ),
        "Vendas"=> array(
            "OLX"=>["origem"=>"Portais","suborigem"=>"OLX"],
            "CHAMADA"=>["origem"=>"Telefone(Receptivo)","suborigem"=>""],
            "VIVA REAL"=>["origem"=>"Portais","suborigem"=>"VivaReal"],
            "IMÓVEL WEB"=>["origem"=>"Portais","suborigem"=>"ImovelWeb"],
            "CHAVES NA MÃO"=>["origem"=>"Portais","suborigem"=>"ChavesNaMao"],
            "MERCADO LIVRE"=>["origem"=>"Portais","suborigem"=>"MercadoLivre"],
            "ZAP IMÓVEIS"=>["origem"=>"Portais","suborigem"=>"ZapImoveis"],
            "FORMULÁRIO DE LOCAÇÃO"=>["origem"=>"SiteLocacao","suborigem"=>""],
            "FORMULÁRIO BUSCA PARA MIM"=>["origem"=>"SiteBusquepMim","suborigem"=>""],
            "FORMULÁRIO DE LEADS"=>["origem"=>"Campanhas","suborigem"=>""],
            "FORMULÁRIO DE VENDAS"=>["origem"=>"SiteLocacao","suborigem"=>""],
            "FORMULÁRIO DE VENDAS - HOTSITE COMERCIAL"=>["origem"=>"SiteLocacaoComercial","suborigem"=>""],
            "FORMULÁRIO CAPTAÇÃO VENDAS"=>["origem"=>"CaptacaoVendas","suborigem"=>""],
            "FORMULÁRIO DE CAPTAÇÃO"=>["origem"=>"CaptacaoLocacao","suborigem"=>""],
            "BLIP"=>["origem"=>"Blip","suborigem"=>""],
            "PORTAL_ESPECIAL"=>["origem"=>"Site","suborigem"=>"Agendamento de Visita"],
        ),
        "Captacao Locacao"=> array(
            "OLX"=>["origem"=>"Portais","suborigem"=>"OLX"],
            "CHAMADA"=>["origem"=>"Telefone(Receptivo)","suborigem"=>""],
            "VIVA REAL"=>["origem"=>"Portais","suborigem"=>"VivaReal"],
            "IMÓVEL WEB"=>["origem"=>"Portais","suborigem"=>"ImovelWeb"],
            "CHAVES NA MÃO"=>["origem"=>"Portais","suborigem"=>"ChavesNaMao"],
            "MERCADO LIVRE"=>["origem"=>"Portais","suborigem"=>"MercadoLivre"],
            "ZAP IMÓVEIS"=>["origem"=>"Portais","suborigem"=>"ZapImoveis"],
            "FORMULÁRIO DE LOCAÇÃO"=>["origem"=>"SiteLocacao","suborigem"=>""],
            "FORMULÁRIO BUSCA PARA MIM"=>["origem"=>"SiteBusquepMim","suborigem"=>""],
            "FORMULÁRIO DE LEADS"=>["origem"=>"Campanhas","suborigem"=>""],
            "FORMULÁRIO DE LOCAÇÃO"=>["origem"=>"SiteLocacao","suborigem"=>""],
            "FORMULÁRIO CAPTAÇÃO VENDAS"=>["origem"=>"CaptacaoVendas","suborigem"=>""],
            "FORMULÁRIO DE CAPTAÇÃO"=>["origem"=>"CaptacaoLocacao","suborigem"=>""],
            "BLIP"=>["origem"=>"Blip","suborigem"=>""],
            "PORTAL_ESPECIAL"=>["origem"=>"Site","suborigem"=>"Agendamento de Visita"],
        ),
        "Captacao Vendas"=> array(
            "OLX"=>["origem"=>"Portais","suborigem"=>"OLX"],
            "CHAMADA"=>["origem"=>"Telefone(Receptivo)","suborigem"=>""],
            "VIVA REAL"=>["origem"=>"Portais","suborigem"=>"VivaReal"],
            "IMÓVEL WEB"=>["origem"=>"Portais","suborigem"=>"ImovelWeb"],
            "CHAVES NA MÃO"=>["origem"=>"Portais","suborigem"=>"ChavesNaMao"],
            "MERCADO LIVRE"=>["origem"=>"Portais","suborigem"=>"MercadoLivre"],
            "ZAP IMÓVEIS"=>["origem"=>"Portais","suborigem"=>"ZapImoveis"],
            "FORMULÁRIO DE LOCAÇÃO"=>["origem"=>"SiteLocacao","suborigem"=>""],
            "FORMULÁRIO BUSCA PARA MIM"=>["origem"=>"SiteBusquepMim","suborigem"=>""],
            "FORMULÁRIO DE LEADS"=>["origem"=>"Campanhas","suborigem"=>""],
            "FORMULÁRIO DE LOCAÇÃO"=>["origem"=>"SiteLocacao","suborigem"=>""],
            "FORMULÁRIO CAPTAÇÃO VENDAS"=>["origem"=>"CaptacaoVendas","suborigem"=>""],
            "FORMULÁRIO DE CAPTAÇÃO"=>["origem"=>"CaptacaoLocacao","suborigem"=>""],
            "BLIP"=>["origem"=>"Blip","suborigem"=>""],
            "PORTAL_ESPECIAL"=>["origem"=>"Site","suborigem"=>"Agendamento de Visita"],
        ),
        "Aluguel_Especial"=> array(
            "OLX"=>["origem"=>"Portais","suborigem"=>"OLX"],
            "CHAMADA"=>["origem"=>"Telefone Especial","suborigem"=>""],
            "VIVA REAL"=>["origem"=>"Portais","suborigem"=>"VivaReal"],
            "IMÓVEL WEB"=>["origem"=>"Portais","suborigem"=>"ImovelWeb"],
            "CHAVES NA MÃO"=>["origem"=>"Portais","suborigem"=>"ChavesNaMao"],
            "MERCADO LIVRE"=>["origem"=>"Portais","suborigem"=>"MercadoLivre"],
            "ZAP IMÓVEIS"=>["origem"=>"Portais","suborigem"=>"ZapImoveis"],
            "FORMULÁRIO DE LOCAÇÃO"=>["origem"=>"","suborigem"=>""],
            "FORMULÁRIO BUSCA PARA MIM"=>["origem"=>"","suborigem"=>""],
            "FORMULÁRIO DE LEADS"=>["origem"=>"Campanhas","suborigem"=>""],
            "FORMULÁRIO DE LOCAÇÃO"=>["origem"=>"","suborigem"=>""],
            "FORMULÁRIO CAPTAÇÃO VENDAS"=>["origem"=>"","suborigem"=>""],
            "FORMULÁRIO DE CAPTAÇÃO"=>["origem"=>"","suborigem"=>""],
            "BLIP"=>["origem"=>"Site","suborigem"=>"Chat"],
            "CANAL_ESPECIAL"=>["origem"=>"Chat Site","suborigem"=>""],
            "PORTAL_ESPECIAL"=>["origem"=>"Site","suborigem"=>"Agendamento de Visita"],
        )
    ),
);
